package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class UIICapabilitiesExtension extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public UIIDeviceIOCapabilities DeviceIO;
    
    public UIIDisplayCapabilities Display;
    
    public UIIRecordingCapabilities Recording;
    
    public UIISearchCapabilities Search;
    
    public UIIReplayCapabilities Replay;
    
    public UIIReceiverCapabilities Receiver;
    
    public UIIAnalyticsDeviceCapabilities AnalyticsDevice;
    
    public UIICapabilitiesExtension2 Extensions;

    

    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DeviceIO"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.DeviceIO = (UIIDeviceIOCapabilities)__envelope.get(j,UIIDeviceIOCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Display"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Display = (UIIDisplayCapabilities)__envelope.get(j,UIIDisplayCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Recording"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Recording = (UIIRecordingCapabilities)__envelope.get(j,UIIRecordingCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Search"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Search = (UIISearchCapabilities)__envelope.get(j,UIISearchCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Replay"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Replay = (UIIReplayCapabilities)__envelope.get(j,UIIReplayCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Receiver"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Receiver = (UIIReceiverCapabilities)__envelope.get(j,UIIReceiverCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("AnalyticsDevice"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AnalyticsDevice = (UIIAnalyticsDeviceCapabilities)__envelope.get(j,UIIAnalyticsDeviceCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Extensions"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extensions = (UIICapabilitiesExtension2)__envelope.get(j,UIICapabilitiesExtension2.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DeviceIO!=null?this.DeviceIO:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.Display!=null?this.Display:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.Recording!=null?this.Recording:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Search!=null?this.Search:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.Replay!=null?this.Replay:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.Receiver!=null?this.Receiver:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.AnalyticsDevice!=null?this.AnalyticsDevice:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.Extensions!=null?this.Extensions:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = UIIDeviceIOCapabilities.class;
                info.name = "DeviceIO";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = UIIDisplayCapabilities.class;
                info.name = "Display";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2)
            {
                info.type = UIIRecordingCapabilities.class;
                info.name = "Recording";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==3)
            {
                info.type = UIISearchCapabilities.class;
                info.name = "Search";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==4)
            {
                info.type = UIIReplayCapabilities.class;
                info.name = "Replay";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==5)
            {
                info.type = UIIReceiverCapabilities.class;
                info.name = "Receiver";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==6)
            {
                info.type = UIIAnalyticsDeviceCapabilities.class;
                info.name = "AnalyticsDevice";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==7)
            {
                info.type = UIICapabilitiesExtension2.class;
                info.name = "Extensions";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
