package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------

import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;
import org.xmlpull.v1.XmlPullParserException;

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;


//If you have a compilation error here then you have to add a reference to ExKsoap2.jar to your project (you can find it in Libs folder in the generated zip file)
public class UIIExtendedSoapSerializationEnvelope extends com.easywsdl.exksoap2.serialization.ExSoapSerializationEnvelope {
    static HashMap< java.lang.String,java.lang.Class> classNames = new HashMap< java.lang.String, java.lang.Class>();
    public static String TAG="easyWSDL";
    static {
        classNames.put("http://www.w3.org/2005/08/addressing^^EndpointReferenceType",UIIEndpointReferenceType.class);
        classNames.put("http://www.w3.org/2005/08/addressing^^ReferenceParametersType",UIIReferenceParametersType.class);
        classNames.put("http://www.w3.org/2005/08/addressing^^MetadataType",UIIMetadataType.class);
        classNames.put("http://docs.oasis-open.org/wsrf/bf-2^^BaseFaultType_ErrorCode",UIIBaseFaultType_ErrorCode.class);
        classNames.put("http://docs.oasis-open.org/wsrf/bf-2^^BaseFaultType_FaultCause",UIIBaseFaultType_FaultCause.class);
        classNames.put("http://docs.oasis-open.org/wsrf/bf-2^^BaseFaultType",UIIBaseFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsrf/r-2^^ResourceUnknownFaultType",UIIResourceUnknownFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsrf/r-2^^ResourceUnavailableFaultType",UIIResourceUnavailableFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^TopicExpressionType",UIITopicExpressionType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^FilterType",UIIFilterType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^NotificationMessageHolderType_Message",UIINotificationMessageHolderType_Message.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^NotificationMessageHolderType",UIINotificationMessageHolderType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^SubscribeCreationFailedFaultType",UIISubscribeCreationFailedFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^InvalidFilterFaultType",UIIInvalidFilterFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^TopicExpressionDialectUnknownFaultType",UIITopicExpressionDialectUnknownFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^InvalidTopicExpressionFaultType",UIIInvalidTopicExpressionFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^TopicNotSupportedFaultType",UIITopicNotSupportedFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^MultipleTopicsSpecifiedFaultType",UIIMultipleTopicsSpecifiedFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^InvalidProducerPropertiesExpressionFaultType",UIIInvalidProducerPropertiesExpressionFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^InvalidMessageContentExpressionFaultType",UIIInvalidMessageContentExpressionFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnrecognizedPolicyRequestFaultType",UIIUnrecognizedPolicyRequestFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnsupportedPolicyRequestFaultType",UIIUnsupportedPolicyRequestFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^NotifyMessageNotSupportedFaultType",UIINotifyMessageNotSupportedFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnacceptableInitialTerminationTimeFaultType",UIIUnacceptableInitialTerminationTimeFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^NoCurrentMessageOnTopicFaultType",UIINoCurrentMessageOnTopicFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnableToGetMessagesFaultType",UIIUnableToGetMessagesFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnableToDestroyPullPointFaultType",UIIUnableToDestroyPullPointFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnableToCreatePullPointFaultType",UIIUnableToCreatePullPointFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnacceptableTerminationTimeFaultType",UIIUnacceptableTerminationTimeFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^UnableToDestroySubscriptionFaultType",UIIUnableToDestroySubscriptionFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^PauseFailedFaultType",UIIPauseFailedFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^ResumeFailedFaultType",UIIResumeFailedFaultType.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^Notify",UIINotify.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^Subscribe_SubscriptionPolicy",UIISubscribe_SubscriptionPolicy.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^SubscribeResponse",UIISubscribeResponse.class);
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^RenewResponse",UIIRenewResponse.class);
        classNames.put("http://www.onvif.org/ver10/events/wsdl^^Capabilities",UIICapabilities.class);
        classNames.put("http://www.onvif.org/ver10/events/wsdl^^CreatePullPointSubscription_SubscriptionPolicy",UIICreatePullPointSubscription_SubscriptionPolicy.class);
        classNames.put("http://www.onvif.org/ver10/events/wsdl^^CreatePullPointSubscriptionResponse",UIICreatePullPointSubscriptionResponse.class);
        classNames.put("http://www.onvif.org/ver10/events/wsdl^^PullMessagesResponse",UIIPullMessagesResponse.class);
        classNames.put("http://www.onvif.org/ver10/events/wsdl^^PullMessagesFaultResponse",UIIPullMessagesFaultResponse.class);
        classNames.put("http://www.w3.org/2004/08/xop/include^^Include",UIIInclude.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector2D",UIIVector2D.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector1D",UIIVector1D.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector",UIIVector.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Rectangle",UIIRectangle.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Color",UIIColor.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceEntity",UIIDeviceEntity.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IntRectangle",UIIIntRectangle.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FloatRange",UIIFloatRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSource",UIIVideoSource.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceExtension",UIIVideoSourceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceExtension2",UIIVideoSourceExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioSource",UIIAudioSource.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Profile",UIIProfile.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ProfileExtension",UIIProfileExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ProfileExtension2",UIIProfileExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ConfigurationEntity",UIIConfigurationEntity.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceConfiguration",UIIVideoSourceConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceConfigurationExtension",UIIVideoSourceConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceConfigurationExtension2",UIIVideoSourceConfigurationExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Rotate",UIIRotate.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RotateExtension",UIIRotateExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LensProjection",UIILensProjection.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LensOffset",UIILensOffset.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LensDescription",UIILensDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SceneOrientation",UIISceneOrientation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoEncoderConfiguration",UIIVideoEncoderConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoResolution",UIIVideoResolution.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoRateControl",UIIVideoRateControl.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Mpeg4Configuration",UIIMpeg4Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^H264Configuration",UIIH264Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoEncoder2Configuration",UIIVideoEncoder2Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoResolution2",UIIVideoResolution2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoRateControl2",UIIVideoRateControl2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioSourceConfiguration",UIIAudioSourceConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioEncoderConfiguration",UIIAudioEncoderConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioEncoder2Configuration",UIIAudioEncoder2Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoAnalyticsConfiguration",UIIVideoAnalyticsConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataConfiguration",UIIMetadataConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataConfigurationExtension",UIIMetadataConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZFilter",UIIPTZFilter.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventSubscription_SubscriptionPolicy",UIIEventSubscription_SubscriptionPolicy.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventSubscription",UIIEventSubscription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutput",UIIVideoOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutputExtension",UIIVideoOutputExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutputConfiguration",UIIVideoOutputConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioOutput",UIIAudioOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioOutputConfiguration",UIIAudioOutputConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioDecoderConfiguration",UIIAudioDecoderConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MulticastConfiguration",UIIMulticastConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Scope",UIIScope.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterface",UIINetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceExtension",UIINetworkInterfaceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot3Configuration",UIIDot3Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceExtension2",UIINetworkInterfaceExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceLink",UIINetworkInterfaceLink.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceConnectionSetting",UIINetworkInterfaceConnectionSetting.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceInfo",UIINetworkInterfaceInfo.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6NetworkInterface",UIIIPv6NetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4NetworkInterface",UIIIPv4NetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4Configuration",UIIIPv4Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6Configuration",UIIIPv6Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6ConfigurationExtension",UIIIPv6ConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkProtocol",UIINetworkProtocol.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkProtocolExtension",UIINetworkProtocolExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkHost",UIINetworkHost.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkHostExtension",UIINetworkHostExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPAddress",UIIIPAddress.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PrefixedIPv4Address",UIIPrefixedIPv4Address.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PrefixedIPv6Address",UIIPrefixedIPv6Address.class);
        classNames.put("http://www.onvif.org/ver10/schema^^HostnameInformation",UIIHostnameInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^HostnameInformationExtension",UIIHostnameInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DNSInformation",UIIDNSInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DNSInformationExtension",UIIDNSInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NTPInformation",UIINTPInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NTPInformationExtension",UIINTPInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DynamicDNSInformation",UIIDynamicDNSInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DynamicDNSInformationExtension",UIIDynamicDNSInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceSetConfiguration",UIINetworkInterfaceSetConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceSetConfigurationExtension",UIINetworkInterfaceSetConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6NetworkInterfaceSetConfiguration",UIIIPv6NetworkInterfaceSetConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4NetworkInterfaceSetConfiguration",UIIIPv4NetworkInterfaceSetConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkGateway",UIINetworkGateway.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11Configuration",UIIDot11Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11SecurityConfiguration",UIIDot11SecurityConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11SecurityConfigurationExtension",UIIDot11SecurityConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11PSKSet",UIIDot11PSKSet.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11PSKSetExtension",UIIDot11PSKSetExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceSetConfigurationExtension2",UIINetworkInterfaceSetConfigurationExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Capabilities",UIICapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/schema^^CapabilitiesExtension",UIICapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^CapabilitiesExtension2",UIICapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsCapabilities",UIIAnalyticsCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceCapabilities",UIIDeviceCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceCapabilitiesExtension",UIIDeviceCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventCapabilities",UIIEventCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IOCapabilities",UIIIOCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IOCapabilitiesExtension",UIIIOCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IOCapabilitiesExtension2",UIIIOCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MediaCapabilities",UIIMediaCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MediaCapabilitiesExtension",UIIMediaCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RealTimeStreamingCapabilities",UIIRealTimeStreamingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RealTimeStreamingCapabilitiesExtension",UIIRealTimeStreamingCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ProfileCapabilities",UIIProfileCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkCapabilities",UIINetworkCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkCapabilitiesExtension",UIINetworkCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkCapabilitiesExtension2",UIINetworkCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SecurityCapabilities",UIISecurityCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SecurityCapabilitiesExtension",UIISecurityCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SecurityCapabilitiesExtension2",UIISecurityCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemCapabilities",UIISystemCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemCapabilitiesExtension",UIISystemCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemCapabilitiesExtension2",UIISystemCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OnvifVersion",UIIOnvifVersion.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingCapabilities",UIIImagingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZCapabilities",UIIPTZCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceIOCapabilities",UIIDeviceIOCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DisplayCapabilities",UIIDisplayCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RecordingCapabilities",UIIRecordingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SearchCapabilities",UIISearchCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ReplayCapabilities",UIIReplayCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ReceiverCapabilities",UIIReceiverCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceCapabilities",UIIAnalyticsDeviceCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceExtension",UIIAnalyticsDeviceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemLog",UIISystemLog.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SupportInformation",UIISupportInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AttachmentData",UIIAttachmentData.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BackupFile",UIIBackupFile.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemDateTime",UIISystemDateTime.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemDateTimeExtension",UIISystemDateTimeExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DateTime",UIIDateTime.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Date",UIIDate.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Time",UIITime.class);
        classNames.put("http://www.onvif.org/ver10/schema^^TimeZone",UIITimeZone.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RemoteUser",UIIRemoteUser.class);
        classNames.put("http://www.onvif.org/ver10/schema^^User",UIIUser.class);
        classNames.put("http://www.onvif.org/ver10/schema^^UserExtension",UIIUserExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RelayOutputSettings",UIIRelayOutputSettings.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RelayOutput",UIIRelayOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DigitalInput",UIIDigitalInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNode",UIIPTZNode.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNodeExtension",UIIPTZNodeExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNodeExtension2",UIIPTZNodeExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPresetTourSupported",UIIPTZPresetTourSupported.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPresetTourSupportedExtension",UIIPTZPresetTourSupportedExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfiguration",UIIPTZConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfigurationExtension",UIIPTZConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfigurationExtension2",UIIPTZConfigurationExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTControlDirection",UIIPTControlDirection.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTControlDirectionExtension",UIIPTControlDirectionExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EFlip",UIIEFlip.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Reverse",UIIReverse.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PanTiltLimits",UIIPanTiltLimits.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ZoomLimits",UIIZoomLimits.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpaces",UIIPTZSpaces.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpacesExtension",UIIPTZSpacesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Space2DDescription",UIISpace2DDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Space1DDescription",UIISpace1DDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpeed",UIIPTZSpeed.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration",UIIFocusConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettings",UIIImagingSettings.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension",UIIImagingSettingsExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Exposure",UIIExposure.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WideDynamicRange",UIIWideDynamicRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BacklightCompensation",UIIBacklightCompensation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance",UIIWhiteBalance.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettings20",UIIImagingSettings20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension20",UIIImagingSettingsExtension20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension202",UIIImagingSettingsExtension202.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension203",UIIImagingSettingsExtension203.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension204",UIIImagingSettingsExtension204.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImageStabilization",UIIImageStabilization.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImageStabilizationExtension",UIIImageStabilizationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IrCutFilterAutoAdjustment",UIIIrCutFilterAutoAdjustment.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IrCutFilterAutoAdjustmentExtension",UIIIrCutFilterAutoAdjustmentExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WideDynamicRange20",UIIWideDynamicRange20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BacklightCompensation20",UIIBacklightCompensation20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Exposure20",UIIExposure20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ToneCompensation",UIIToneCompensation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ToneCompensationExtension",UIIToneCompensationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Defogging",UIIDefogging.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DefoggingExtension",UIIDefoggingExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NoiseReduction",UIINoiseReduction.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance20",UIIWhiteBalance20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance20Extension",UIIWhiteBalance20Extension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration20",UIIFocusConfiguration20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration20Extension",UIIFocusConfiguration20Extension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemList_SimpleItem",UIIItemList_SimpleItem.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemList_ElementItem",UIIItemList_ElementItem.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemList",UIIItemList.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemListExtension",UIIItemListExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineConfiguration",UIIAnalyticsEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineConfigurationExtension",UIIAnalyticsEngineConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RuleEngineConfiguration",UIIRuleEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RuleEngineConfigurationExtension",UIIRuleEngineConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Config",UIIConfig.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PaneLayout",UIIPaneLayout.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Layout",UIILayout.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LayoutExtension",UIILayoutExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventFilter",UIIEventFilter.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngine",UIIAnalyticsEngine.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceEngineConfiguration",UIIAnalyticsDeviceEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceEngineConfigurationExtension",UIIAnalyticsDeviceEngineConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EngineConfiguration",UIIEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineInputInfo",UIIAnalyticsEngineInputInfo.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineInputInfoExtension",UIIAnalyticsEngineInputInfoExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineInput",UIIAnalyticsEngineInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SourceIdentification",UIISourceIdentification.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SourceIdentificationExtension",UIISourceIdentificationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataInput",UIIMetadataInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataInputExtension",UIIMetadataInputExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineControl",UIIAnalyticsEngineControl.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDPosConfiguration",UIIOSDPosConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDPosConfigurationExtension",UIIOSDPosConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDColor",UIIOSDColor.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDTextConfiguration",UIIOSDTextConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDTextConfigurationExtension",UIIOSDTextConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDImgConfiguration",UIIOSDImgConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDImgConfigurationExtension",UIIOSDImgConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDConfiguration",UIIOSDConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDConfigurationExtension",UIIOSDConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^Capabilities",UIICapabilities_2.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^ProfileCapabilities",UIIProfileCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^StreamingCapabilities",UIIStreamingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^Service_Capabilities",UIIService_Capabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^Service",UIIService.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^DeviceServiceCapabilities",UIIDeviceServiceCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^NetworkCapabilities",UIINetworkCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SecurityCapabilities",UIISecurityCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SystemCapabilities",UIISystemCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^MiscCapabilities",UIIMiscCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^UserCredential_Extension",UIIUserCredential_Extension.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^UserCredential",UIIUserCredential.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^StorageConfigurationData_Extension",UIIStorageConfigurationData_Extension.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^StorageConfigurationData",UIIStorageConfigurationData.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^StorageConfiguration",UIIStorageConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetDeviceInformationResponse",UIIGetDeviceInformationResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetDNS",UIISetDNS.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetNTP",UIISetNTP.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetVideoSourcesResponse",UIIGetVideoSourcesResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetAudioSourcesResponse",UIIGetAudioSourcesResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetAudioOutputsResponse",UIIGetAudioOutputsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetProfilesResponse",UIIGetProfilesResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetVideoEncoderConfigurationsResponse",UIIGetVideoEncoderConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetVideoSourceConfigurationsResponse",UIIGetVideoSourceConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetAudioEncoderConfigurationsResponse",UIIGetAudioEncoderConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetAudioSourceConfigurationsResponse",UIIGetAudioSourceConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetVideoAnalyticsConfigurationsResponse",UIIGetVideoAnalyticsConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetMetadataConfigurationsResponse",UIIGetMetadataConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetAudioOutputConfigurationsResponse",UIIGetAudioOutputConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/media/wsdl^^GetAudioDecoderConfigurationsResponse",UIIGetAudioDecoderConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetServicesResponse",UIIGetServicesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^RestoreSystem",UIIRestoreSystem.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetSystemBackupResponse",UIIGetSystemBackupResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetScopesResponse",UIIGetScopesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetScopes",UIISetScopes.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^AddScopes",UIIAddScopes.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^RemoveScopes",UIIRemoveScopes.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^RemoveScopesResponse",UIIRemoveScopesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetDPAddressesResponse",UIIGetDPAddressesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetDPAddresses",UIISetDPAddresses.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetUsersResponse",UIIGetUsersResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^CreateUsers",UIICreateUsers.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^DeleteUsers",UIIDeleteUsers.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetUser",UIISetUser.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetCapabilities",UIIGetCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetNetworkInterfacesResponse",UIIGetNetworkInterfacesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetNetworkProtocolsResponse",UIIGetNetworkProtocolsResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetNetworkProtocols",UIISetNetworkProtocols.class);
    } 

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";
    public boolean enableLogging;

    public static void setDateTimeConverter(UIIDateTimeConverter converter)
    {
        if(converter==null)
        {
            dateTimeConverter = new UIIStandardDateTimeConverter();
        }
        dateTimeConverter=converter;
    }

    public static UIIDateTimeConverter getDateTimeConverter()
    {
        return dateTimeConverter;
    }

    private static UIIDateTimeConverter dateTimeConverter = new UIIStandardDateTimeConverter();

    public UIIExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public UIIExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new UIIMarshalGuid().register(this);
        new MarshalFloat().register(this);
    }


    @Override
    public void writeBody(XmlSerializer writer) throws IOException {
        if(this.bodyOut instanceof SoapObject)
        {
            SoapObject root=(SoapObject)this.bodyOut;
            if(root.getName().equals("") && root.getNamespace().equals(""))
            {
                Field declaredField =  null;
                try {

                    Vector multiRef = new Vector();
                    multiRef.addElement(this.bodyOut);

                    declaredField = SoapSerializationEnvelope.class.getDeclaredField("multiRef");
                    boolean accessible = declaredField.isAccessible();
                    declaredField.setAccessible(true);
                    declaredField.set(this, multiRef);
                    declaredField.setAccessible(accessible);

                } catch (NoSuchFieldException
                        | SecurityException
                        | IllegalArgumentException
                        | IllegalAccessException e) {
                    e.printStackTrace();
                }

                this.writeElement(writer, this.bodyOut, (PropertyInfo)null, null);
                return;
            }
        }
        super.writeBody(writer);
    }

    @Override
    protected void writeProperty(XmlSerializer writer, java.lang.Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        if(writeReferenceObject(writer,obj))
        {
            return;
        }
        java.lang.Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {
            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=java.lang.String.class  )) {
                java.lang.String xmlName=UIIHelper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    java.lang.String[] parts = xmlName.split("\\^\\^");
                    java.lang.String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        java.lang.String xsdPrefix = writer.getPrefix(xsd, true);
                        java.lang.String myType = (java.lang.String) type.type;
                        java.lang.String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        java.lang.String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement,java.lang.String exceptionElementNS,java.lang.String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception e)
        {
			if(enableLogging)
			{
				android.util.Log.e(UIIExtendedSoapSerializationEnvelope.TAG,"Error occured",e);
			}
        }
        return null;
    }

    public java.lang.Object GetHeader(Element detailElement) {
        if(detailElement.getChildCount()>0 && detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    private Object createObject(Object soap, Class cl) throws InstantiationException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {
        Object obj=cl.newInstance();
        Method ctor = obj.getClass().getMethod("loadFromSoap",Object.class,UIIExtendedSoapSerializationEnvelope.class);
        ctor.invoke(obj,soap,this);
        return obj;
    }

    public java.lang.Object get(java.lang.Object soap,java.lang.Class cl,boolean typeFromClass)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(typeFromClass)
            {
                return createObject(soap, cl);
            }
            java.lang.Object refAttr=getReference(soap);
            if (refAttr != null)
            {
                return refAttr;
            }
            else
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    java.lang.String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                return createObject(soap, cl);
            }
        }
        catch (java.lang.Exception e)
        {
			if(enableLogging)
			{
				android.util.Log.e(UIIExtendedSoapSerializationEnvelope.TAG,"Error occured",e);
			}
            return null;
        }
    }


    public java.lang.Object getSpecificType(java.lang.Object obj)
    {
        if(obj==null)
        {
            return null;
        }
        if(obj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)obj;
            java.lang.String key=soapObject.getNamespace()+"^^"+soapObject.getName();
            if(classNames.containsKey(key))
            {
                java.lang.Class cl=classNames.get(key);
                try
                {
                    return createObject(soapObject, cl);
                } 
                catch (java.lang.Exception e)
                {
					if(enableLogging)
					{
						android.util.Log.e(UIIExtendedSoapSerializationEnvelope.TAG,"Error occured",e);
					}
                }
            }
        }

        return obj;
    }

    public static java.lang.Object getXSDType(java.lang.Object param)
    {
        if(param==null)
        {
            return null;
        }
        java.lang.Class obj=param.getClass();
        if(obj.equals(java.lang.String.class))
        {
            return "string";
        }
        if(obj.equals(int.class) || obj.equals(java.lang.Integer.class))
        {
            return "int";
        }
        if(obj.equals(float.class) || obj.equals(java.lang.Float.class))
        {
            return "float";
        }
        if(obj.equals(double.class) || obj.equals(java.lang.Double.class))
        {
            return "double";
        }
        if(obj.equals(java.math.BigDecimal.class))
        {
            return "decimal";
        }
        if(obj.equals(short.class) || obj.equals(java.lang.Short.class))
        {
            return "short";
        }
        if(obj.equals(long.class) || obj.equals(java.lang.Long.class))
        {
            return "long";
        }
        if(obj.equals(boolean.class) || obj.equals(java.lang.Boolean.class))
        {
            return "boolean";
        }
        java.lang.String xmlName=UIIHelper.getKeyByValue(classNames,obj);
        if(xmlName==null)
        {
            return obj;
        }
        return xmlName;
    }
} 

