package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class UIIImagingSettingsExtension202 extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public java.util.ArrayList< UIIIrCutFilterAutoAdjustment> IrCutFilterAutoAdjustment =new java.util.ArrayList<UIIIrCutFilterAutoAdjustment >();
    
    public UIIImagingSettingsExtension203 Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IrCutFilterAutoAdjustment"))
        {
            if(obj!=null)
            {
                if(this.IrCutFilterAutoAdjustment==null)
                {
                    this.IrCutFilterAutoAdjustment = new java.util.ArrayList< UIIIrCutFilterAutoAdjustment>();
                }
                java.lang.Object j =obj;
                UIIIrCutFilterAutoAdjustment j1= (UIIIrCutFilterAutoAdjustment)__envelope.get(j,UIIIrCutFilterAutoAdjustment.class,false);
                this.IrCutFilterAutoAdjustment.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (UIIImagingSettingsExtension203)__envelope.get(j,UIIImagingSettingsExtension203.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.IrCutFilterAutoAdjustment.size())
        {
            UIIIrCutFilterAutoAdjustment IrCutFilterAutoAdjustment = this.IrCutFilterAutoAdjustment.get(propertyIndex-(0));
            return IrCutFilterAutoAdjustment!=null?IrCutFilterAutoAdjustment:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==0+this.IrCutFilterAutoAdjustment.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+IrCutFilterAutoAdjustment.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex>=0 && propertyIndex < 0+this.IrCutFilterAutoAdjustment.size())
            {
                info.type = UIIIrCutFilterAutoAdjustment.class;
                info.name = "IrCutFilterAutoAdjustment";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==0+this.IrCutFilterAutoAdjustment.size())
            {
                info.type = UIIImagingSettingsExtension203.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
