package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class UIINetworkInterfaceExtension extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Integer InterfaceType=0;
    
    public java.util.ArrayList< UIIDot3Configuration> Dot3 =new java.util.ArrayList<UIIDot3Configuration >();
    
    public java.util.ArrayList< UIIDot11Configuration> Dot11 =new java.util.ArrayList<UIIDot11Configuration >();
    
    public UIINetworkInterfaceExtension2 Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("InterfaceType"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InterfaceType = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.InterfaceType = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Dot3"))
        {
            if(obj!=null)
            {
                if(this.Dot3==null)
                {
                    this.Dot3 = new java.util.ArrayList< UIIDot3Configuration>();
                }
                java.lang.Object j =obj;
                UIIDot3Configuration j1= (UIIDot3Configuration)__envelope.get(j,UIIDot3Configuration.class,false);
                this.Dot3.add(j1);
            }
            return true;
        }
        if (info.name.equals("Dot11"))
        {
            if(obj!=null)
            {
                if(this.Dot11==null)
                {
                    this.Dot11 = new java.util.ArrayList< UIIDot11Configuration>();
                }
                java.lang.Object j =obj;
                UIIDot11Configuration j1= (UIIDot11Configuration)__envelope.get(j,UIIDot11Configuration.class,false);
                this.Dot11.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (UIINetworkInterfaceExtension2)__envelope.get(j,UIINetworkInterfaceExtension2.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.InterfaceType;
        }
        else if(propertyIndex>=1 && propertyIndex < 1+this.Dot3.size())
        {
            UIIDot3Configuration Dot3 = this.Dot3.get(propertyIndex-(1));
            return Dot3!=null?Dot3:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=1+this.Dot3.size() && propertyIndex < 1+this.Dot3.size()+this.Dot11.size())
        {
            UIIDot11Configuration Dot11 = this.Dot11.get(propertyIndex-(1+this.Dot3.size()));
            return Dot11!=null?Dot11:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1+this.Dot3.size()+this.Dot11.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+Dot3.size()+Dot11.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "InterfaceType";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=1 && propertyIndex < 1+this.Dot3.size())
            {
                info.type = UIIDot3Configuration.class;
                info.name = "Dot3";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=1+this.Dot3.size() && propertyIndex < 1+this.Dot3.size()+this.Dot11.size())
            {
                info.type = UIIDot11Configuration.class;
                info.name = "Dot11";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1+this.Dot3.size()+this.Dot11.size())
            {
                info.type = UIINetworkInterfaceExtension2.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
