package net.petrocik.onvif.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class UIIOperationResult< T>
{
    
    public java.lang.Exception Exception;
    
    public T Result;
    
    public java.lang.Object Tag;
    
    public java.lang.String MethodName;
}
