package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class UIIProfileExtension extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public UIIAudioOutputConfiguration AudioOutputConfiguration;
    
    public UIIAudioDecoderConfiguration AudioDecoderConfiguration;
    
    public UIIProfileExtension2 Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("AudioOutputConfiguration"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AudioOutputConfiguration = (UIIAudioOutputConfiguration)__envelope.get(j,UIIAudioOutputConfiguration.class,false);
            }
            return true;
        }
        if (info.name.equals("AudioDecoderConfiguration"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AudioDecoderConfiguration = (UIIAudioDecoderConfiguration)__envelope.get(j,UIIAudioDecoderConfiguration.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (UIIProfileExtension2)__envelope.get(j,UIIProfileExtension2.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AudioOutputConfiguration!=null?this.AudioOutputConfiguration:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.AudioDecoderConfiguration!=null?this.AudioDecoderConfiguration:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = UIIAudioOutputConfiguration.class;
                info.name = "AudioOutputConfiguration";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = UIIAudioDecoderConfiguration.class;
                info.name = "AudioDecoderConfiguration";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2)
            {
                info.type = UIIProfileExtension2.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
