package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class UIIStorageConfigurationData extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public String LocalPath;
    
    public String StorageUri;
    
    public UIIUserCredential User;
    
    public UIIStorageConfigurationData_Extension Extension;
    
    public String type;

    

    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

		if (inObj.hasAttribute("type"))
        {	
            java.lang.Object j = inObj.getAttribute("type");
            if (j != null)
            {
                type = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("LocalPath"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LocalPath = j.toString();
                    }
                }
                else{
                    this.LocalPath = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("StorageUri"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StorageUri = j.toString();
                    }
                }
                else{
                    this.StorageUri = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("User"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.User = (UIIUserCredential)__envelope.get(j,UIIUserCredential.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (UIIStorageConfigurationData_Extension)__envelope.get(j,UIIStorageConfigurationData_Extension.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.LocalPath!=null?this.LocalPath:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.StorageUri!=null?this.StorageUri:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.User!=null?this.User:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocalPath";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "StorageUri";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex==2)
            {
                info.type = UIIUserCredential.class;
                info.name = "User";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex==3)
            {
                info.type = UIIStorageConfigurationData_Extension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



        public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
if(index==0)
        {
            info.name = "type";
            info.namespace= "";
            if(this.type!=null)
            {
                info.setValue(this.type);
            }
        
        }
        
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}
