package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class UIISetNTP extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Boolean FromDHCP=false;
    
    public java.util.ArrayList< UIINetworkHost> NTPManual =new java.util.ArrayList<UIINetworkHost >();

    

    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("FromDHCP"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FromDHCP = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.FromDHCP = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NTPManual"))
        {
            if(obj!=null)
            {
                if(this.NTPManual==null)
                {
                    this.NTPManual = new java.util.ArrayList< UIINetworkHost>();
                }
                java.lang.Object j =obj;
                UIINetworkHost j1= (UIINetworkHost)__envelope.get(j,UIINetworkHost.class,false);
                this.NTPManual.add(j1);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.FromDHCP;
        }
        else if(propertyIndex>=1 && propertyIndex < 1+this.NTPManual.size())
        {
            UIINetworkHost NTPManual = this.NTPManual.get(propertyIndex-(1));
            return NTPManual!=null?NTPManual:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+NTPManual.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FromDHCP";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex>=1 && propertyIndex < 1+this.NTPManual.size())
            {
                info.type = UIINetworkHost.class;
                info.name = "NTPManual";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
