package net.petrocik.onvif.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class UIIVideoSourceConfiguration extends UIIConfigurationEntity implements KvmSerializable
{

    
    public String SourceToken;
    
    public UIIIntRectangle Bounds;
    
    public UIIVideoSourceConfigurationExtension Extension;

    

    @Override
    public void loadFromSoap(java.lang.Object paramObj,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);


    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,UIIExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("SourceToken"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SourceToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SourceToken = (String)obj;
                }
                else{
                    this.SourceToken = "";
                }
            }
            return true;
        }
        if (info.name.equals("Bounds"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Bounds = (UIIIntRectangle)__envelope.get(j,UIIIntRectangle.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (UIIVideoSourceConfigurationExtension)__envelope.get(j,UIIVideoSourceConfigurationExtension.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.SourceToken;
        }
        else if(propertyIndex==count+1)
        {
            return this.Bounds;
        }
        else if(propertyIndex==count+2)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            int count = super.getPropertyCount();
            if(propertyIndex==count+0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SourceToken";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+1)
            {
                info.type = UIIIntRectangle.class;
                info.name = "Bounds";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+2)
            {
                info.type = UIIVideoSourceConfigurationExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
