package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class BaseFaultType extends org.ksoap2.SoapFault implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public java.util.Date Timestamp;
    
    public EndpointReferenceType Originator;
    
    public BaseFaultType_ErrorCode ErrorCode;
    
    public java.util.ArrayList< BaseFaultType_Description> Description =new java.util.ArrayList<BaseFaultType_Description >();
    
    public BaseFaultType_FaultCause FaultCause;
    
    public java.util.ArrayList< PropertyInfo> any =new java.util.ArrayList< PropertyInfo>();

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                    info= __envelope.getAny(info);
                    this.any.add(info);
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Timestamp"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Timestamp = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.Timestamp = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Originator"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Originator = (EndpointReferenceType)__envelope.get(j,EndpointReferenceType.class,false);
            }
            return true;
        }
        if (info.name.equals("ErrorCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ErrorCode = (BaseFaultType_ErrorCode)__envelope.get(j,BaseFaultType_ErrorCode.class,false);
            }
            return true;
        }
        if (info.name.equals("Description"))
        {
            if(obj!=null)
            {
                if(this.Description==null)
                {
                    this.Description = new java.util.ArrayList< BaseFaultType_Description>();
                }
                java.lang.Object j =obj;
                BaseFaultType_Description j1= (BaseFaultType_Description)__envelope.get(j,BaseFaultType_Description.class,false);
                this.Description.add(j1);
            }
            return true;
        }
        if (info.name.equals("FaultCause"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FaultCause = (BaseFaultType_FaultCause)__envelope.get(j,BaseFaultType_FaultCause.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Timestamp!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.Timestamp):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.Originator!=null?this.Originator:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.ErrorCode!=null?this.ErrorCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=3 && propertyIndex < 3+this.Description.size())
        {
            return this.Description.get(propertyIndex-(3)).getSimpleValue();
        }
        else if(propertyIndex==3+this.Description.size())
        {
            return this.FaultCause!=null?this.FaultCause:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=4+this.Description.size() && propertyIndex < 4+this.Description.size()+this.any.size())
        {
            return this.any.get(propertyIndex-(4+this.Description.size())).getValue();
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4+Description.size()+ any.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Timestamp";
                info.namespace= "http://docs.oasis-open.org/wsrf/bf-2";
            }
            else if(propertyIndex==1)
            {
                info.type = EndpointReferenceType.class;
                info.name = "Originator";
                info.namespace= "http://docs.oasis-open.org/wsrf/bf-2";
            }
            else if(propertyIndex==2)
            {
                info.type = BaseFaultType_ErrorCode.class;
                info.name = "ErrorCode";
                info.namespace= "http://docs.oasis-open.org/wsrf/bf-2";
            }
            else if(propertyIndex>=3 && propertyIndex < 3+this.Description.size())
            {
                info.type = org.ksoap2.serialization.SoapPrimitive.class;
                info.name = "Description";
                info.namespace= "http://docs.oasis-open.org/wsrf/bf-2";
            }
            else if(propertyIndex==3+this.Description.size())
            {
                info.type = BaseFaultType_FaultCause.class;
                info.name = "FaultCause";
                info.namespace= "http://docs.oasis-open.org/wsrf/bf-2";
            }
            else if(propertyIndex>=4+this.Description.size() && propertyIndex < 4+this.Description.size()+this.any.size())
            {
                PropertyInfo j=this.any.get(propertyIndex-(4+this.Description.size()));
                info.type = j.type;
                info.name = j.name;
                info.namespace= j.namespace;
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
