package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class Capabilities extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Boolean WSSubscriptionPolicySupport=false;
    
    public Boolean WSPullPointSupport=false;
    
    public Boolean WSPausableSubscriptionManagerInterfaceSupport=false;
    
    public Integer MaxNotificationProducers=0;
    
    public Integer MaxPullPoints=0;
    
    public Boolean PersistentNotificationStorage=false;
    
    public java.util.ArrayList< PropertyInfo> any =new java.util.ArrayList< PropertyInfo>();

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                    info= __envelope.getAny(info);
                    this.any.add(info);
                }
            } 
        }

		if (inObj.hasAttribute("WSSubscriptionPolicySupport"))
        {	
            java.lang.Object j = inObj.getAttribute("WSSubscriptionPolicySupport");
            if (j != null)
            {
                WSSubscriptionPolicySupport = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("WSPullPointSupport"))
        {	
            java.lang.Object j = inObj.getAttribute("WSPullPointSupport");
            if (j != null)
            {
                WSPullPointSupport = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("WSPausableSubscriptionManagerInterfaceSupport"))
        {	
            java.lang.Object j = inObj.getAttribute("WSPausableSubscriptionManagerInterfaceSupport");
            if (j != null)
            {
                WSPausableSubscriptionManagerInterfaceSupport = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("MaxNotificationProducers"))
        {	
            java.lang.Object j = inObj.getAttribute("MaxNotificationProducers");
            if (j != null)
            {
                MaxNotificationProducers = Integer.parseInt(j.toString());
            }
        }
		if (inObj.hasAttribute("MaxPullPoints"))
        {	
            java.lang.Object j = inObj.getAttribute("MaxPullPoints");
            if (j != null)
            {
                MaxPullPoints = Integer.parseInt(j.toString());
            }
        }
		if (inObj.hasAttribute("PersistentNotificationStorage"))
        {	
            java.lang.Object j = inObj.getAttribute("PersistentNotificationStorage");
            if (j != null)
            {
                PersistentNotificationStorage = Boolean.valueOf(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.any.size())
        {
            return this.any.get(propertyIndex-(0)).getValue();
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0+ any.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex>=0 && propertyIndex < 0+this.any.size())
            {
                PropertyInfo j=this.any.get(propertyIndex-(0));
                info.type = j.type;
                info.name = j.name;
                info.namespace= j.namespace;
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



        public int getAttributeCount() {
        return 6;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
if(index==0)
        {
            info.name = "WSSubscriptionPolicySupport";
            info.namespace= "";
            if(this.WSSubscriptionPolicySupport!=null)
            {
                info.setValue(this.WSSubscriptionPolicySupport);
            }
        
        }
        if(index==1)
        {
            info.name = "WSPullPointSupport";
            info.namespace= "";
            if(this.WSPullPointSupport!=null)
            {
                info.setValue(this.WSPullPointSupport);
            }
        
        }
        if(index==2)
        {
            info.name = "WSPausableSubscriptionManagerInterfaceSupport";
            info.namespace= "";
            if(this.WSPausableSubscriptionManagerInterfaceSupport!=null)
            {
                info.setValue(this.WSPausableSubscriptionManagerInterfaceSupport);
            }
        
        }
        if(index==3)
        {
            info.name = "MaxNotificationProducers";
            info.namespace= "";
            if(this.MaxNotificationProducers!=null)
            {
                info.setValue(this.MaxNotificationProducers);
            }
        
        }
        if(index==4)
        {
            info.name = "MaxPullPoints";
            info.namespace= "";
            if(this.MaxPullPoints!=null)
            {
                info.setValue(this.MaxPullPoints);
            }
        
        }
        if(index==5)
        {
            info.name = "PersistentNotificationStorage";
            info.namespace= "";
            if(this.PersistentNotificationStorage!=null)
            {
                info.setValue(this.PersistentNotificationStorage);
            }
        
        }
        
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}
