package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class DeviceServiceCapabilities extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public NetworkCapabilities_1 Network;
    
    public SecurityCapabilities_1 Security;
    
    public SystemCapabilities_1 System;
    
    public MiscCapabilities Misc;

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Network"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Network = (NetworkCapabilities_1)__envelope.get(j,NetworkCapabilities_1.class,false);
            }
            return true;
        }
        if (info.name.equals("Security"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Security = (SecurityCapabilities_1)__envelope.get(j,SecurityCapabilities_1.class,false);
            }
            return true;
        }
        if (info.name.equals("System"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.System = (SystemCapabilities_1)__envelope.get(j,SystemCapabilities_1.class,false);
            }
            return true;
        }
        if (info.name.equals("Misc"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Misc = (MiscCapabilities)__envelope.get(j,MiscCapabilities.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Network;
        }
        else if(propertyIndex==1)
        {
            return this.Security;
        }
        else if(propertyIndex==2)
        {
            return this.System;
        }
        else if(propertyIndex==3)
        {
            return this.Misc!=null?this.Misc:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = NetworkCapabilities_1.class;
                info.name = "Network";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex==1)
            {
                info.type = SecurityCapabilities_1.class;
                info.name = "Security";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex==2)
            {
                info.type = SystemCapabilities_1.class;
                info.name = "System";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
            else if(propertyIndex==3)
            {
                info.type = MiscCapabilities.class;
                info.name = "Misc";
                info.namespace= "http://www.onvif.org/ver10/device/wsdl";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
