package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class Dot1XConfiguration extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public String Dot1XConfigurationToken;
    
    public String Identity;
    
    public String AnonymousID;
    
    public Integer EAPMethod=0;
    
    public java.util.ArrayList< String> CACertificateID =new java.util.ArrayList<String >();
    
    public EAPMethodConfiguration EAPMethodConfiguration;
    
    public Dot1XConfigurationExtension Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Dot1XConfigurationToken"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Dot1XConfigurationToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Dot1XConfigurationToken = (String)obj;
                }
                else{
                    this.Dot1XConfigurationToken = "";
                }
            }
            return true;
        }
        if (info.name.equals("Identity"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Identity = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Identity = (String)obj;
                }
                else{
                    this.Identity = "";
                }
            }
            return true;
        }
        if (info.name.equals("AnonymousID"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AnonymousID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AnonymousID = (String)obj;
                }
                else{
                    this.AnonymousID = "";
                }
            }
            return true;
        }
        if (info.name.equals("EAPMethod"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EAPMethod = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EAPMethod = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CACertificateID"))
        {
            if(obj!=null)
            {
                if(this.CACertificateID==null)
                {
                    this.CACertificateID = new java.util.ArrayList< String>();
                }
                java.lang.Object j =obj;
                String j1= j.toString();
                this.CACertificateID.add(j1);
            }
            return true;
        }
        if (info.name.equals("EAPMethodConfiguration"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.EAPMethodConfiguration = (EAPMethodConfiguration)__envelope.get(j,EAPMethodConfiguration.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (Dot1XConfigurationExtension)__envelope.get(j,Dot1XConfigurationExtension.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Dot1XConfigurationToken;
        }
        else if(propertyIndex==1)
        {
            return this.Identity;
        }
        else if(propertyIndex==2)
        {
            return this.AnonymousID!=null?this.AnonymousID:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.EAPMethod;
        }
        else if(propertyIndex>=4 && propertyIndex < 4+this.CACertificateID.size())
        {
            String CACertificateID = this.CACertificateID.get(propertyIndex-(4));
            return CACertificateID!=null?CACertificateID:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4+this.CACertificateID.size())
        {
            return this.EAPMethodConfiguration!=null?this.EAPMethodConfiguration:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5+this.CACertificateID.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6+CACertificateID.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Dot1XConfigurationToken";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Identity";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "AnonymousID";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==3)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "EAPMethod";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=4 && propertyIndex < 4+this.CACertificateID.size())
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CACertificateID";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==4+this.CACertificateID.size())
            {
                info.type = EAPMethodConfiguration.class;
                info.name = "EAPMethodConfiguration";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==5+this.CACertificateID.size())
            {
                info.type = Dot1XConfigurationExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
