package net.petrocik.onvif;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------



import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class ImagingBinding
{
    interface IWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="";

    int timeOut=60000;
    
    public List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    public boolean enableLogging;
    public boolean createClassesForAny = false;

    IServiceEvents callback;

    public ImagingBinding(){}

    public ImagingBinding (IServiceEvents callback)
    {
        this.callback = callback;
    }
    public ImagingBinding(IServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public ImagingBinding(IServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                String path=uri.getPath();
                if(uri.getQuery()!=null && uri.getQuery()!="")
                {
                    path+="?"+uri.getQuery();
                }
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, path, timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER12);
        envelope.enableLogging = enableLogging;
        envelope.createClassesForAny = createClassesForAny;
    
        return envelope;
    }

    protected java.util.List sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) 
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }

    
    
    
    public Capabilities_4 GetServiceCapabilities() throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Capabilities_4)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "GetServiceCapabilities");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (Capabilities_4)getResult(Capabilities_4.class,__result,"Capabilities",__envelope);
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/GetServiceCapabilities",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< Capabilities_4>> GetServiceCapabilitiesAsync()
    {
        return executeAsync(new Functions.IFunc< Capabilities_4>() {
            public Capabilities_4 Func() throws java.lang.Exception {
                return GetServiceCapabilities( );
            }
        },"GetServiceCapabilities");
    }
    
    
    
    public ImagingSettings20 GetImagingSettings(final String VideoSourceToken) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ImagingSettings20)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "GetImagingSettings");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ImagingSettings20)getResult(ImagingSettings20.class,__result,"ImagingSettings",__envelope);
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/GetImagingSettings",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< ImagingSettings20>> GetImagingSettingsAsync(final String VideoSourceToken)
    {
        return executeAsync(new Functions.IFunc< ImagingSettings20>() {
            public ImagingSettings20 Func() throws java.lang.Exception {
                return GetImagingSettings( VideoSourceToken);
            }
        },"GetImagingSettings");
    }
    
    
    
    public void SetImagingSettings(final String VideoSourceToken,final ImagingSettings20 ImagingSettings,final Boolean ForcePersistence) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.onvif.org/ver20/imaging/wsdl","ImagingSettings",ImagingSettings20.class);
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "SetImagingSettings");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="ImagingSettings";
                __info.type=ImagingSettings20.class;
                __info.setValue(ImagingSettings);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="ForcePersistence";
                __info.type=PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(ForcePersistence!=null?ForcePersistence:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/SetImagingSettings",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< Void>> SetImagingSettingsAsync(final String VideoSourceToken,final ImagingSettings20 ImagingSettings,final Boolean ForcePersistence)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                SetImagingSettings( VideoSourceToken,ImagingSettings,ForcePersistence);
                return null;
            }
        },"SetImagingSettings") ;
    }
    
    
    
    public ImagingOptions20 GetOptions(final String VideoSourceToken) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ImagingOptions20)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "GetOptions");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ImagingOptions20)getResult(ImagingOptions20.class,__result,"ImagingOptions",__envelope);
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/GetOptions",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< ImagingOptions20>> GetOptionsAsync(final String VideoSourceToken)
    {
        return executeAsync(new Functions.IFunc< ImagingOptions20>() {
            public ImagingOptions20 Func() throws java.lang.Exception {
                return GetOptions( VideoSourceToken);
            }
        },"GetOptions");
    }
    
    
    
    public void Move(final String VideoSourceToken,final FocusMove Focus) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.onvif.org/ver20/imaging/wsdl","Focus",FocusMove.class);
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "Move");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="Focus";
                __info.type=FocusMove.class;
                __info.setValue(Focus);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/Move",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< Void>> MoveAsync(final String VideoSourceToken,final FocusMove Focus)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                Move( VideoSourceToken,Focus);
                return null;
            }
        },"Move") ;
    }
    
    
    
    public MoveOptions20 GetMoveOptions(final String VideoSourceToken) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (MoveOptions20)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "GetMoveOptions");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MoveOptions20)getResult(MoveOptions20.class,__result,"MoveOptions",__envelope);
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/GetMoveOptions",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< MoveOptions20>> GetMoveOptionsAsync(final String VideoSourceToken)
    {
        return executeAsync(new Functions.IFunc< MoveOptions20>() {
            public MoveOptions20 Func() throws java.lang.Exception {
                return GetMoveOptions( VideoSourceToken);
            }
        },"GetMoveOptions");
    }
    
    
    
    public void Stop(final String VideoSourceToken) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "Stop");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/FocusStop",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< Void>> StopAsync(final String VideoSourceToken)
    {
        return executeAsync(new Functions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                Stop( VideoSourceToken);
                return null;
            }
        },"Stop") ;
    }
    
    
    
    public ImagingStatus20 GetStatus(final String VideoSourceToken) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ImagingStatus20)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/imaging/wsdl", "GetStatus");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/imaging/wsdl";
                __info.name="VideoSourceToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(VideoSourceToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ImagingStatus20)getResult(ImagingStatus20.class,__result,"Status",__envelope);
            }
        },"http://www.onvif.org/ver20/imaging/wsdl/GetStatus",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< ImagingStatus20>> GetStatusAsync(final String VideoSourceToken)
    {
        return executeAsync(new Functions.IFunc< ImagingStatus20>() {
            public ImagingStatus20 Func() throws java.lang.Exception {
                return GetStatus( VideoSourceToken);
            }
        },"GetStatus");
    }

    protected java.lang.Object execute(IWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }

    protected < T> android.os.AsyncTask< Void, Void, OperationResult< T>>  executeAsync(final Functions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.MethodName=methodName;
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }

    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;
        return newException;
    }
}


