package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class IPAddressFilter extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Enums.IPAddressFilterType Type=Enums.IPAddressFilterType.Allow;
    
    public java.util.ArrayList< PrefixedIPv4Address> IPv4Address =new java.util.ArrayList<PrefixedIPv4Address >();
    
    public java.util.ArrayList< PrefixedIPv6Address> IPv6Address =new java.util.ArrayList<PrefixedIPv6Address >();
    
    public IPAddressFilterExtension Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Type"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Type = Enums.IPAddressFilterType.fromString(j.toString());
                    }
                }
                else if (obj instanceof Enums.IPAddressFilterType){
                    this.Type = (Enums.IPAddressFilterType)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IPv4Address"))
        {
            if(obj!=null)
            {
                if(this.IPv4Address==null)
                {
                    this.IPv4Address = new java.util.ArrayList< PrefixedIPv4Address>();
                }
                java.lang.Object j =obj;
                PrefixedIPv4Address j1= (PrefixedIPv4Address)__envelope.get(j,PrefixedIPv4Address.class,false);
                this.IPv4Address.add(j1);
            }
            return true;
        }
        if (info.name.equals("IPv6Address"))
        {
            if(obj!=null)
            {
                if(this.IPv6Address==null)
                {
                    this.IPv6Address = new java.util.ArrayList< PrefixedIPv6Address>();
                }
                java.lang.Object j =obj;
                PrefixedIPv6Address j1= (PrefixedIPv6Address)__envelope.get(j,PrefixedIPv6Address.class,false);
                this.IPv6Address.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (IPAddressFilterExtension)__envelope.get(j,IPAddressFilterExtension.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Type!=null?this.Type.toString():SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=1 && propertyIndex < 1+this.IPv4Address.size())
        {
            PrefixedIPv4Address IPv4Address = this.IPv4Address.get(propertyIndex-(1));
            return IPv4Address!=null?IPv4Address:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=1+this.IPv4Address.size() && propertyIndex < 1+this.IPv4Address.size()+this.IPv6Address.size())
        {
            PrefixedIPv6Address IPv6Address = this.IPv6Address.get(propertyIndex-(1+this.IPv4Address.size()));
            return IPv6Address!=null?IPv6Address:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1+this.IPv4Address.size()+this.IPv6Address.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+IPv4Address.size()+IPv6Address.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Type";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=1 && propertyIndex < 1+this.IPv4Address.size())
            {
                info.type = PrefixedIPv4Address.class;
                info.name = "IPv4Address";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=1+this.IPv4Address.size() && propertyIndex < 1+this.IPv4Address.size()+this.IPv6Address.size())
            {
                info.type = PrefixedIPv6Address.class;
                info.name = "IPv6Address";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1+this.IPv4Address.size()+this.IPv6Address.size())
            {
                info.type = IPAddressFilterExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
