package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class MetadataConfiguration extends ConfigurationEntity implements KvmSerializable
{

    
    public PTZFilter PTZStatus;
    
    public EventSubscription Events;
    
    public Boolean Analytics;
    
    public MulticastConfiguration Multicast;
    
    public String SessionTimeout;
    
    public AnalyticsEngineConfiguration AnalyticsEngineConfiguration;
    
    public MetadataConfigurationExtension Extension;
    
    public String CompressionType;
    
    public Boolean GeoLocation=false;
    
    public Boolean ShapePolygon=false;

    

    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

		if (inObj.hasAttribute("CompressionType"))
        {	
            java.lang.Object j = inObj.getAttribute("CompressionType");
            if (j != null)
            {
                CompressionType = j.toString();
            }
        }
		if (inObj.hasAttribute("GeoLocation"))
        {	
            java.lang.Object j = inObj.getAttribute("GeoLocation");
            if (j != null)
            {
                GeoLocation = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("ShapePolygon"))
        {	
            java.lang.Object j = inObj.getAttribute("ShapePolygon");
            if (j != null)
            {
                ShapePolygon = Boolean.valueOf(j.toString());
            }
        }

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("PTZStatus"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PTZStatus = (PTZFilter)__envelope.get(j,PTZFilter.class,false);
            }
            return true;
        }
        if (info.name.equals("Events"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Events = (EventSubscription)__envelope.get(j,EventSubscription.class,false);
            }
            return true;
        }
        if (info.name.equals("Analytics"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Analytics = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Analytics = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Multicast"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Multicast = (MulticastConfiguration)__envelope.get(j,MulticastConfiguration.class,false);
            }
            return true;
        }
        if (info.name.equals("SessionTimeout"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SessionTimeout = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDuration(j.toString());
                    }
                }
                else if (obj instanceof String){
                    this.SessionTimeout = (String)obj;
                }
                else{
                    this.SessionTimeout = "";
                }
            }
            return true;
        }
        if (info.name.equals("AnalyticsEngineConfiguration"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AnalyticsEngineConfiguration = (AnalyticsEngineConfiguration)__envelope.get(j,AnalyticsEngineConfiguration.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (MetadataConfigurationExtension)__envelope.get(j,MetadataConfigurationExtension.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.PTZStatus!=null?this.PTZStatus:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+1)
        {
            return this.Events!=null?this.Events:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+2)
        {
            return this.Analytics!=null?this.Analytics:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+3)
        {
            return this.Multicast;
        }
        else if(propertyIndex==count+4)
        {
            return this.SessionTimeout!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDuration(this.SessionTimeout):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+5)
        {
            return this.AnalyticsEngineConfiguration!=null?this.AnalyticsEngineConfiguration:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+6)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            int count = super.getPropertyCount();
            if(propertyIndex==count+0)
            {
                info.type = PTZFilter.class;
                info.name = "PTZStatus";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+1)
            {
                info.type = EventSubscription.class;
                info.name = "Events";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+2)
            {
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Analytics";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+3)
            {
                info.type = MulticastConfiguration.class;
                info.name = "Multicast";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+4)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SessionTimeout";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+5)
            {
                info.type = AnalyticsEngineConfiguration.class;
                info.name = "AnalyticsEngineConfiguration";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+6)
            {
                info.type = MetadataConfigurationExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



        public int getAttributeCount() {
        return super.getAttributeCount() + 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        int count=super.getAttributeCount();
if(index==count+0)
        {
            info.name = "CompressionType";
            info.namespace= "";
            if(this.CompressionType!=null)
            {
                info.setValue(this.CompressionType);
            }
        
        }
        if(index==count+1)
        {
            info.name = "GeoLocation";
            info.namespace= "";
            if(this.GeoLocation!=null)
            {
                info.setValue(this.GeoLocation);
            }
        
        }
        if(index==count+2)
        {
            info.name = "ShapePolygon";
            info.namespace= "";
            if(this.ShapePolygon!=null)
            {
                info.setValue(this.ShapePolygon);
            }
        
        }
                if(index < count)
        {
            super.getAttributeInfo(index, info);
        }

    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}
