package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class NetworkInterface extends DeviceEntity implements KvmSerializable
{

    
    public Boolean Enabled=false;
    
    public NetworkInterfaceInfo Info;
    
    public NetworkInterfaceLink Link;
    
    public IPv4NetworkInterface IPv4;
    
    public IPv6NetworkInterface IPv6;
    
    public NetworkInterfaceExtension Extension;

    

    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);


    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Enabled"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Enabled = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Enabled = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Info"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Info = (NetworkInterfaceInfo)__envelope.get(j,NetworkInterfaceInfo.class,false);
            }
            return true;
        }
        if (info.name.equals("Link"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Link = (NetworkInterfaceLink)__envelope.get(j,NetworkInterfaceLink.class,false);
            }
            return true;
        }
        if (info.name.equals("IPv4"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.IPv4 = (IPv4NetworkInterface)__envelope.get(j,IPv4NetworkInterface.class,false);
            }
            return true;
        }
        if (info.name.equals("IPv6"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.IPv6 = (IPv6NetworkInterface)__envelope.get(j,IPv6NetworkInterface.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (NetworkInterfaceExtension)__envelope.get(j,NetworkInterfaceExtension.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.Enabled;
        }
        else if(propertyIndex==count+1)
        {
            return this.Info!=null?this.Info:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+2)
        {
            return this.Link!=null?this.Link:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+3)
        {
            return this.IPv4!=null?this.IPv4:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+4)
        {
            return this.IPv6!=null?this.IPv6:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+5)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            int count = super.getPropertyCount();
            if(propertyIndex==count+0)
            {
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Enabled";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+1)
            {
                info.type = NetworkInterfaceInfo.class;
                info.name = "Info";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+2)
            {
                info.type = NetworkInterfaceLink.class;
                info.name = "Link";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+3)
            {
                info.type = IPv4NetworkInterface.class;
                info.name = "IPv4";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+4)
            {
                info.type = IPv6NetworkInterface.class;
                info.name = "IPv6";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==count+5)
            {
                info.type = NetworkInterfaceExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
