package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class Notify extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public java.util.ArrayList< NotificationMessageHolderType> NotificationMessage =new java.util.ArrayList<NotificationMessageHolderType >();
    
    public java.util.ArrayList< PropertyInfo> any =new java.util.ArrayList< PropertyInfo>();

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                    info= __envelope.getAny(info);
                    this.any.add(info);
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("NotificationMessage"))
        {
            if(obj!=null)
            {
                if(this.NotificationMessage==null)
                {
                    this.NotificationMessage = new java.util.ArrayList< NotificationMessageHolderType>();
                }
                java.lang.Object j =obj;
                NotificationMessageHolderType j1= (NotificationMessageHolderType)__envelope.get(j,NotificationMessageHolderType.class,false);
                this.NotificationMessage.add(j1);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.NotificationMessage.size())
        {
            NotificationMessageHolderType NotificationMessage = this.NotificationMessage.get(propertyIndex-(0));
            return NotificationMessage;
        }
        else if(propertyIndex>=0+this.NotificationMessage.size() && propertyIndex < 0+this.NotificationMessage.size()+this.any.size())
        {
            return this.any.get(propertyIndex-(0+this.NotificationMessage.size())).getValue();
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0+NotificationMessage.size()+ any.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex>=0 && propertyIndex < 0+this.NotificationMessage.size())
            {
                info.type = NotificationMessageHolderType.class;
                info.name = "NotificationMessage";
                info.namespace= "http://docs.oasis-open.org/wsn/b-2";
            }
            else if(propertyIndex>=0+this.NotificationMessage.size() && propertyIndex < 0+this.NotificationMessage.size()+this.any.size())
            {
                PropertyInfo j=this.any.get(propertyIndex-(0+this.NotificationMessage.size()));
                info.type = j.type;
                info.name = j.name;
                info.namespace= j.namespace;
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
