package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class PTZPresetTourSpot extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public PTZPresetTourPresetDetail PresetDetail;
    
    public PTZSpeed Speed;
    
    public String StayTime;
    
    public PTZPresetTourSpotExtension Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("PresetDetail"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PresetDetail = (PTZPresetTourPresetDetail)__envelope.get(j,PTZPresetTourPresetDetail.class,false);
            }
            return true;
        }
        if (info.name.equals("Speed"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Speed = (PTZSpeed)__envelope.get(j,PTZSpeed.class,false);
            }
            return true;
        }
        if (info.name.equals("StayTime"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StayTime = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDuration(j.toString());
                    }
                }
                else if (obj instanceof String){
                    this.StayTime = (String)obj;
                }
                else{
                    this.StayTime = "";
                }
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (PTZPresetTourSpotExtension)__envelope.get(j,PTZPresetTourSpotExtension.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.PresetDetail;
        }
        else if(propertyIndex==1)
        {
            return this.Speed!=null?this.Speed:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.StayTime!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDuration(this.StayTime):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PTZPresetTourPresetDetail.class;
                info.name = "PresetDetail";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = PTZSpeed.class;
                info.name = "Speed";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "StayTime";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==3)
            {
                info.type = PTZPresetTourSpotExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
