package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class PTZPresetTourStartingConditionOptions extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public IntRange RecurringTime;
    
    public DurationRange RecurringDuration;
    
    public java.util.ArrayList< Enums.PTZPresetTourDirection> Direction =new java.util.ArrayList<Enums.PTZPresetTourDirection >();
    
    public PTZPresetTourStartingConditionOptionsExtension Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("RecurringTime"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RecurringTime = (IntRange)__envelope.get(j,IntRange.class,false);
            }
            return true;
        }
        if (info.name.equals("RecurringDuration"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RecurringDuration = (DurationRange)__envelope.get(j,DurationRange.class,false);
            }
            return true;
        }
        if (info.name.equals("Direction"))
        {
            if(obj!=null)
            {
                if(this.Direction==null)
                {
                    this.Direction = new java.util.ArrayList< Enums.PTZPresetTourDirection>();
                }
                java.lang.Object j =obj;
                Enums.PTZPresetTourDirection j1= Enums.PTZPresetTourDirection.fromString(j.toString());
                this.Direction.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (PTZPresetTourStartingConditionOptionsExtension)__envelope.get(j,PTZPresetTourStartingConditionOptionsExtension.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.RecurringTime!=null?this.RecurringTime:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.RecurringDuration!=null?this.RecurringDuration:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=2 && propertyIndex < 2+this.Direction.size())
        {
            Enums.PTZPresetTourDirection Direction = this.Direction.get(propertyIndex-(2));
            return Direction!=null?Direction.toString():SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2+this.Direction.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3+Direction.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = IntRange.class;
                info.name = "RecurringTime";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = DurationRange.class;
                info.name = "RecurringDuration";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=2 && propertyIndex < 2+this.Direction.size())
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Direction";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2+this.Direction.size())
            {
                info.type = PTZPresetTourStartingConditionOptionsExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
