package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class PTZStatus extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public PTZVector Position;
    
    public PTZMoveStatus MoveStatus;
    
    public String Error;
    
    public java.util.Date UtcTime;
    
    public java.util.ArrayList< PropertyInfo> any =new java.util.ArrayList< PropertyInfo>();

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                    info= __envelope.getAny(info);
                    this.any.add(info);
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Position"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Position = (PTZVector)__envelope.get(j,PTZVector.class,false);
            }
            return true;
        }
        if (info.name.equals("MoveStatus"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.MoveStatus = (PTZMoveStatus)__envelope.get(j,PTZMoveStatus.class,false);
            }
            return true;
        }
        if (info.name.equals("Error"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Error = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Error = (String)obj;
                }
                else{
                    this.Error = "";
                }
            }
            return true;
        }
        if (info.name.equals("UtcTime"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UtcTime = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.UtcTime = (java.util.Date)obj;
                }
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Position!=null?this.Position:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.MoveStatus!=null?this.MoveStatus:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.Error!=null?this.Error:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.UtcTime!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.UtcTime):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex>=4 && propertyIndex < 4+this.any.size())
        {
            return this.any.get(propertyIndex-(4)).getValue();
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4+ any.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PTZVector.class;
                info.name = "Position";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = PTZMoveStatus.class;
                info.name = "MoveStatus";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Error";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==3)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "UtcTime";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex>=4 && propertyIndex < 4+this.any.size())
            {
                PropertyInfo j=this.any.get(propertyIndex-(4));
                info.type = j.type;
                info.name = j.name;
                info.namespace= j.namespace;
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
