package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class StreamingCapabilities extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Boolean RTPMulticast=false;
    
    public Boolean RTP_TCP=false;
    
    public Boolean RTP_RTSP_TCP=false;
    
    public Boolean NonAggregateControl=false;
    
    public Boolean NoRTSPStreaming=false;
    
    public java.util.ArrayList< PropertyInfo> any =new java.util.ArrayList< PropertyInfo>();

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                    info= __envelope.getAny(info);
                    this.any.add(info);
                }
            } 
        }

		if (inObj.hasAttribute("RTPMulticast"))
        {	
            java.lang.Object j = inObj.getAttribute("RTPMulticast");
            if (j != null)
            {
                RTPMulticast = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("RTP_TCP"))
        {	
            java.lang.Object j = inObj.getAttribute("RTP_TCP");
            if (j != null)
            {
                RTP_TCP = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("RTP_RTSP_TCP"))
        {	
            java.lang.Object j = inObj.getAttribute("RTP_RTSP_TCP");
            if (j != null)
            {
                RTP_RTSP_TCP = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("NonAggregateControl"))
        {	
            java.lang.Object j = inObj.getAttribute("NonAggregateControl");
            if (j != null)
            {
                NonAggregateControl = Boolean.valueOf(j.toString());
            }
        }
		if (inObj.hasAttribute("NoRTSPStreaming"))
        {	
            java.lang.Object j = inObj.getAttribute("NoRTSPStreaming");
            if (j != null)
            {
                NoRTSPStreaming = Boolean.valueOf(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.any.size())
        {
            return this.any.get(propertyIndex-(0)).getValue();
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0+ any.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex>=0 && propertyIndex < 0+this.any.size())
            {
                PropertyInfo j=this.any.get(propertyIndex-(0));
                info.type = j.type;
                info.name = j.name;
                info.namespace= j.namespace;
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



        public int getAttributeCount() {
        return 5;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
if(index==0)
        {
            info.name = "RTPMulticast";
            info.namespace= "";
            if(this.RTPMulticast!=null)
            {
                info.setValue(this.RTPMulticast);
            }
        
        }
        if(index==1)
        {
            info.name = "RTP_TCP";
            info.namespace= "";
            if(this.RTP_TCP!=null)
            {
                info.setValue(this.RTP_TCP);
            }
        
        }
        if(index==2)
        {
            info.name = "RTP_RTSP_TCP";
            info.namespace= "";
            if(this.RTP_RTSP_TCP!=null)
            {
                info.setValue(this.RTP_RTSP_TCP);
            }
        
        }
        if(index==3)
        {
            info.name = "NonAggregateControl";
            info.namespace= "";
            if(this.NonAggregateControl!=null)
            {
                info.setValue(this.NonAggregateControl);
            }
        
        }
        if(index==4)
        {
            info.name = "NoRTSPStreaming";
            info.namespace= "";
            if(this.NoRTSPStreaming!=null)
            {
                info.setValue(this.NoRTSPStreaming);
            }
        
        }
        
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}
