package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class SystemDateTime extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Enums.SetDateTimeType DateTimeType=Enums.SetDateTimeType.Manual;
    
    public Boolean DaylightSavings=false;
    
    public TimeZone TimeZone;
    
    public DateTime UTCDateTime;
    
    public DateTime LocalDateTime;
    
    public SystemDateTimeExtension Extension;

    

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DateTimeType"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateTimeType = Enums.SetDateTimeType.fromString(j.toString());
                    }
                }
                else if (obj instanceof Enums.SetDateTimeType){
                    this.DateTimeType = (Enums.SetDateTimeType)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DaylightSavings"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DaylightSavings = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DaylightSavings = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TimeZone"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TimeZone = (TimeZone)__envelope.get(j,TimeZone.class,false);
            }
            return true;
        }
        if (info.name.equals("UTCDateTime"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.UTCDateTime = (DateTime)__envelope.get(j,DateTime.class,false);
            }
            return true;
        }
        if (info.name.equals("LocalDateTime"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LocalDateTime = (DateTime)__envelope.get(j,DateTime.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (SystemDateTimeExtension)__envelope.get(j,SystemDateTimeExtension.class,false);
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DateTimeType!=null?this.DateTimeType.toString():SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.DaylightSavings;
        }
        else if(propertyIndex==2)
        {
            return this.TimeZone!=null?this.TimeZone:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.UTCDateTime!=null?this.UTCDateTime:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.LocalDateTime!=null?this.LocalDateTime:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DateTimeType";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "DaylightSavings";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==2)
            {
                info.type = TimeZone.class;
                info.name = "TimeZone";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==3)
            {
                info.type = DateTime.class;
                info.name = "UTCDateTime";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==4)
            {
                info.type = DateTime.class;
                info.name = "LocalDateTime";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
            else if(propertyIndex==5)
            {
                info.type = SystemDateTimeExtension.class;
                info.name = "Extension";
                info.namespace= "http://www.onvif.org/ver10/schema";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
