package net.petrocik.onvif;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public  class TopicNamespaceType extends ExtensibleDocumented implements KvmSerializable
{

    
    public java.util.ArrayList< TopicNamespaceType_Topic> Topic =new java.util.ArrayList<TopicNamespaceType_Topic >();
    
    public String name;
    
    public String targetNamespace;
    
    public Boolean _final=false;

    

    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

		if (inObj.hasAttribute("name"))
        {	
            java.lang.Object j = inObj.getAttribute("name");
            if (j != null)
            {
                name = j.toString();
            }
        }
		if (inObj.hasAttribute("targetNamespace"))
        {	
            java.lang.Object j = inObj.getAttribute("targetNamespace");
            if (j != null)
            {
                targetNamespace = j.toString();
            }
        }
		if (inObj.hasAttribute("final"))
        {	
            java.lang.Object j = inObj.getAttribute("final");
            if (j != null)
            {
                _final = Boolean.valueOf(j.toString());
            }
        }

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Topic"))
        {
            if(obj!=null)
            {
                if(this.Topic==null)
                {
                    this.Topic = new java.util.ArrayList< TopicNamespaceType_Topic>();
                }
                java.lang.Object j =obj;
                TopicNamespaceType_Topic j1= (TopicNamespaceType_Topic)__envelope.get(j,TopicNamespaceType_Topic.class,false);
                this.Topic.add(j1);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=count+0 && propertyIndex < count+0+this.Topic.size())
        {
            TopicNamespaceType_Topic Topic = this.Topic.get(propertyIndex-(count+0));
            return Topic!=null?Topic:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+0+Topic.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            int count = super.getPropertyCount();
            if(propertyIndex>=count+0 && propertyIndex < count+0+this.Topic.size())
            {
                info.type = TopicNamespaceType_Topic.class;
                info.name = "Topic";
                info.namespace= "http://docs.oasis-open.org/wsn/t-1";
            }
            super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



        public int getAttributeCount() {
        return 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
if(index==0)
        {
            info.name = "name";
            info.namespace= "";
            if(this.name!=null)
            {
                info.setValue(this.name);
            }
        
        }
        if(index==1)
        {
            info.name = "targetNamespace";
            info.namespace= "";
            if(this.targetNamespace!=null)
            {
                info.setValue(this.targetNamespace);
            }
        
        }
        if(index==2)
        {
            info.name = "final";
            info.namespace= "";
            if(this._final!=null)
            {
                info.setValue(this._final);
            }
        
        }
        
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}
